/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author johand
 */
public class Principal extends javax.swing.JFrame {
    
    Inicio inicio;    
    VistaPaciente vistaPaciente;
    VistaEnfermedades vistaEnfermedad;
    VistaMedicamentos vistaMedicamento;
    VistaDiagnostico vistaDiagnostico;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //this.setLocationRelativeTo(this);
        inicio=new Inicio();
        inicio.setSize(this.getWidth()-1,this.getHeight()-1);
        this.setContentPane(inicio);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jmInicio = new javax.swing.JMenuItem();
        jmPacientes = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmEnfermedad = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmMedicamentos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu5.setText("Pacientes");

        jmInicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmInicio.setText("Inicio");
        jmInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInicioActionPerformed(evt);
            }
        });
        jMenu5.add(jmInicio);

        jmPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmPacientes.setText("Lista");
        jmPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPacientesActionPerformed(evt);
            }
        });
        jMenu5.add(jmPacientes);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Enfermedades");

        jmEnfermedad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmEnfermedad.setText("Lista");
        jmEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEnfermedadActionPerformed(evt);
            }
        });
        jMenu6.add(jmEnfermedad);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Medicamentos");

        jmMedicamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmMedicamentos.setText("Lista");
        jmMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMedicamentosActionPerformed(evt);
            }
        });
        jMenu7.add(jmMedicamentos);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPacientesActionPerformed
        vistaPaciente=new VistaPaciente();
        vistaPaciente.setSize(this.getWidth(),this.getHeight());
        vistaPaciente.setPrincipal(this);
        vistaPaciente.setVisible(true);        
        setContentPane(vistaPaciente);        
    }//GEN-LAST:event_jmPacientesActionPerformed

    private void jmInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInicioActionPerformed
        jmPacientes.setEnabled(true);
        jmMedicamentos.setEnabled(true);
        jmEnfermedad.setEnabled(true);        
        this.setContentPane(inicio);
    }//GEN-LAST:event_jmInicioActionPerformed

    private void jmEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEnfermedadActionPerformed
        vistaEnfermedad=new VistaEnfermedades();        
        vistaEnfermedad.setSize(getWidth(),getHeight());
        vistaEnfermedad.setVisible(true);        
        setContentPane(vistaEnfermedad);
    }//GEN-LAST:event_jmEnfermedadActionPerformed

    private void jmMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMedicamentosActionPerformed
        vistaMedicamento=new VistaMedicamentos();
        vistaMedicamento.setSize(this.getWidth(),this.getHeight());
        vistaMedicamento.setVisible(true);        
        setContentPane(vistaMedicamento);
        repaint();
    }//GEN-LAST:event_jmMedicamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmEnfermedad;
    private javax.swing.JMenuItem jmInicio;
    private javax.swing.JMenuItem jmMedicamentos;
    private javax.swing.JMenuItem jmPacientes;
    // End of variables declaration//GEN-END:variables

    
}
