/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.EnfermedadCtrl;
import Controlador.FormulaCtrl;
import Controlador.MedicamentoCtrl;
import Controlador.MedicamentoFormulaCtrl;
import Controlador.PacienteCtrl;
import Controlador.PacienteEnfermedadCtrl;
import java.awt.Image;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Enfermedad;

/**
 *
 * @author johand
 */
public class VistaDiagnostico extends javax.swing.JPanel {
    FormulaCtrl control;
    EnfermedadCtrl enfermedadCtrl;
    MedicamentoCtrl medicamentoCtrl;
    PacienteEnfermedadCtrl pacienteEnfermo;
    MedicamentoFormulaCtrl medixFormula;
    DefaultComboBoxModel modelo;
    DefaultListModel modeloCmb;
    
    

    /**
     * Creates new form vistaDiagnostico
     */
    public VistaDiagnostico() {
        initComponents();
        validarEstado();
        control=new FormulaCtrl();        
        enfermedadCtrl=new EnfermedadCtrl();
        medicamentoCtrl=new MedicamentoCtrl();
        pacienteEnfermo=new PacienteEnfermedadCtrl();
        medixFormula=new MedicamentoFormulaCtrl();
        modelo=new DefaultComboBoxModel();
        modeloCmb=new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaEnfermedad = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDescripcionEnfermedad = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        lblEstadoPaciente = new javax.swing.JLabel();
        cmbPadecimiento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEnfermar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblTipoEnfermedad = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMedicamentos = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnFormular = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();
        btnAsociarEnfermedad = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 0));
        setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        setForeground(new java.awt.Color(255, 255, 255));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotosPacientes/user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        lblNombre.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblNombre.setText("----------------------");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setText("Cedula:");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setText("Genero:");

        lblEdad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblEdad.setText("----");

        lblCedula.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblCedula.setText("----------------------");

        lblGenero.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblGenero.setText("-----------");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("INFORMACION");

        jLabel1.setText("--------------------------------------------------------------------------------------------------------------------");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Enfermedades");

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Lista:");

        lstListaEnfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListaEnfermedadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstListaEnfermedad);

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Descripcion:");

        txtaDescripcionEnfermedad.setColumns(20);
        txtaDescripcionEnfermedad.setRows(5);
        txtaDescripcionEnfermedad.setEnabled(false);
        jScrollPane2.setViewportView(txtaDescripcionEnfermedad);

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Estado:");

        lblEstadoPaciente.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblEstadoPaciente.setText("Sano");

        cmbPadecimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setText("Padecimientos:");

        jLabel14.setText("--------------------------------------------------------------------------------------------------------------------");

        btnEnfermar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/enfermar.png"))); // NOI18N
        btnEnfermar.setToolTipText("Enfermar");
        btnEnfermar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfermarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel15.setText("Tipo:");

        lblTipoEnfermedad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        lblTipoEnfermedad.setText("---------");

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setText("Formulacion");

        lstMedicamentos.setEnabled(false);
        jScrollPane3.setViewportView(lstMedicamentos);

        jLabel17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel17.setText("Medicamento");

        jLabel19.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel19.setText("Descripcion");

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setRows(5);
        txtaDescripcion.setEnabled(false);
        jScrollPane4.setViewportView(txtaDescripcion);

        jLabel20.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel20.setText("Fecha:");

        txtFecha.setEnabled(false);

        btnFormular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/formular.png"))); // NOI18N
        btnFormular.setToolTipText("Formular");
        btnFormular.setEnabled(false);
        btnFormular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormularActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        lblError.setToolTipText("");

        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mostrarFormula.png"))); // NOI18N
        btnGuardarCambios.setEnabled(false);
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        btnAsociarEnfermedad.setText("...");
        btnAsociarEnfermedad.setToolTipText("GuardarInfoEnfermedades");
        btnAsociarEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarEnfermedadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel19))
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(70, 70, 70))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(btnFormular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnfermar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAsociarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipoEnfermedad)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombre)
                                            .addComponent(lblCedula))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEdad)
                                            .addComponent(lblGenero)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEstadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lblEstadoPaciente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblEdad)
                            .addComponent(jLabel2)
                            .addComponent(lblNombre))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblCedula)
                            .addComponent(jLabel6)
                            .addComponent(lblGenero)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblTipoEnfermedad)
                    .addComponent(jLabel7))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEnfermar)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cmbPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsociarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel19))
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFecha)
                                .addGap(1, 1, 1)))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormular)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnfermarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnfermarActionPerformed
        try{
            if(validarDuplicado()){
                cargarModeloCombo(modelo);
                cargarMedicamento(lstListaEnfermedad.getSelectedValue());
                lblError.setText("");
            }           
        }catch(NullPointerException npe){
            lblError.setText("no ha seleccionado nada");
        }
    }//GEN-LAST:event_btnEnfermarActionPerformed

    private void btnAsociarEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarEnfermedadActionPerformed
        try{    
            for(int i=0;i<cmbPadecimiento.getItemCount();i++){
                if(!cmbPadecimiento.getItemAt(i).equals("Seleccionar")){                    
                    pacienteEnfermo.adicionarPacienteEnfermo(Integer.parseInt(lblCedula.getText()),(String)cmbPadecimiento.getItemAt(i));            
                }
            }
            JOptionPane.showMessageDialog(null,"Datos de enfermedades adicionados","informacion",JOptionPane.INFORMATION_MESSAGE);
            validarEstado();
            lblError.setText("");
        }catch(NullPointerException npe){
            lblError.setText("null pointer");
        }
    }//GEN-LAST:event_btnAsociarEnfermedadActionPerformed

    private void lstListaEnfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListaEnfermedadMouseClicked
        try{    
            infoEnfermedades();
            lblError.setText("");
        }catch(NullPointerException npe){
            lblError.setText(npe.getMessage());
        }
    }//GEN-LAST:event_lstListaEnfermedadMouseClicked

    private void btnFormularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormularActionPerformed
        if(validarCampos()){
            control.adicionarFormula(Integer.parseInt(lblCedula.getText()),txtaDescripcion.getText(),txtFecha.getText());        
            adicionarMedicamentos();        
            btnGuardarCambios.setEnabled(true);
        }
    }//GEN-LAST:event_btnFormularActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        pacienteEnfermo.guardarEnfermedadxPaciente();
        medixFormula.guardarMedicamentoxFormula();
        control.guardarFormulas();
        deshabilitarVentana();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociarEnfermedad;
    private javax.swing.JButton btnEnfermar;
    private javax.swing.JButton btnFormular;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JComboBox<String> cmbPadecimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblEstadoPaciente;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipoEnfermedad;
    private javax.swing.JList<String> lstListaEnfermedad;
    private javax.swing.JList<String> lstMedicamentos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextArea txtaDescripcion;
    private javax.swing.JTextArea txtaDescripcionEnfermedad;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos(){
        if(txtaDescripcion.getText().equals("")||txtFecha.getText().equals("")){
            return false;
        }
        return true;
    }
    
    private void deshabilitarVentana(){
        btnAsociarEnfermedad.setEnabled(false);
        btnEnfermar.setEnabled(false);
        btnFormular.setEnabled(false);
        btnGuardarCambios.setEnabled(false);
        cmbPadecimiento.setEnabled(false);
        lstListaEnfermedad.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Paciente Formulado");       
    }
    
    public void cargarPaciente(int cedula,int edad,String nombre,String genero,String foto){
        lblCedula.setText(Integer.toString(cedula));
        lblEdad.setText(Integer.toString(edad));
        lblNombre.setText(nombre);
        lblGenero.setText(genero);        
        cargarFoto(foto);
         
    }

    private void cargarFoto(String foto) {
        repaint();
        ImageIcon img=new ImageIcon(foto);
        Icon icono=new ImageIcon(img.getImage().getScaledInstance(50,45,Image.SCALE_DEFAULT));
        lblFoto.setIcon(icono);
        
    }
    
    private void validarSalud(){
        if(lblEstadoPaciente.getText().equals("Sano")){
            btnFormular.setEnabled(false);
            txtaDescripcion.setEnabled(false);
            txtFecha.setEnabled(false);            
        }else{
            btnFormular.setEnabled(true);
            txtaDescripcion.setEnabled(true);
            txtFecha.setEnabled(true);            
        }
    }
    
    private void validarEstado(){        
        if(!cmbPadecimiento.getSelectedItem().equals("Seleccionar")){
            lblEstadoPaciente.setText("Enfermo");
        }
        validarSalud();
    }
    
    public void cargarEnfermedades(DefaultListModel modelo){        
        lstListaEnfermedad.setModel(modelo);
        lstListaEnfermedad.updateUI();
        
    }
    
    private void infoEnfermedades(){        
        txtaDescripcionEnfermedad.setText(enfermedadCtrl.buscarEnfermedades(lstListaEnfermedad.getSelectedValue()).getDescripcion());
        lblTipoEnfermedad.setText(enfermedadCtrl.buscarEnfermedades(lstListaEnfermedad.getSelectedValue()).getTipoEnfermedad());
    }

    private void cargarModeloCombo(DefaultComboBoxModel modelo){        
        modelo.addElement(lstListaEnfermedad.getSelectedValue());
        cmbPadecimiento.setModel(modelo);
        cmbPadecimiento.updateUI();
    }
    
    private void cargarMedicamento(String dato){            
        for(int i=0;i<enfermedadCtrl.getListaEnfermedades().size();i++){
            if(enfermedadCtrl.getListaEnfermedades().get(i).getNombre().equals(dato)){
                if(enfermedadCtrl.buscarEnfermedades(dato).getTipoEnfermedad().equals("Tipo1")){
                    for(int j=0;j<medicamentoCtrl.getListaMedicina().size();j++){
                        if(medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo1")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo2")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo3")){
                            modeloCmb.addElement(medicamentoCtrl.getListaMedicina().get(i).getNombre());
                        }
                    }
                }
                if(enfermedadCtrl.buscarEnfermedades(dato).getTipoEnfermedad().equals("Tipo2")){
                    for(int j=0;j<medicamentoCtrl.getListaMedicina().size();j++){
                        if(medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo4")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo5")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo6")){
                            modeloCmb.addElement(medicamentoCtrl.getListaMedicina().get(i).getNombre());
                        }
                    }
                }
                if(enfermedadCtrl.buscarEnfermedades(dato).getTipoEnfermedad().equals("Tipo3")){
                    for(int j=0;j<medicamentoCtrl.getListaMedicina().size();j++){
                        if(medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo7")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo8")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo9")){
                            modeloCmb.addElement(medicamentoCtrl.getListaMedicina().get(i).getNombre());
                        }
                    }
                }
                if(enfermedadCtrl.buscarEnfermedades(dato).getTipoEnfermedad().equals("Tipo4")){
                    for(int j=0;j<medicamentoCtrl.getListaMedicina().size();j++){
                        if(medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo10")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo11")||medicamentoCtrl.getListaMedicina().get(j).getTipo().equals("Tipo12")){
                            modeloCmb.addElement(medicamentoCtrl.getListaMedicina().get(i).getNombre());
                        }
                    }
                }                                
            }
        }
        lstMedicamentos.setModel(modeloCmb);     
        lstMedicamentos.updateUI();
    }
    
    private boolean validarDuplicado(){
        for(int i=0;i<cmbPadecimiento.getItemCount();i++){    
            if(lstListaEnfermedad.getSelectedValue().equals(cmbPadecimiento.getItemAt(i))){
                return false;
            }
        }
        return true;
    }

    private void adicionarMedicamentos() {
        DefaultListModel modelo=new DefaultListModel();
        modelo=(DefaultListModel) lstMedicamentos.getModel();
        for(int i=0;i<modelo.size();i++){
            medixFormula.adicionarMedicamento(lblCedula.getText(),(String) modelo.elementAt(i));            
        }
    }
    
}
